# Test configuration for daemon with CLI enabled

daemon:
  test_interval: 60        # 1 minute for testing
  workers: 2               # Small number for testing
  batch_size: 10
  
database:
  type: "duckdb"
  duckdb:
    nodes_path: "./nodelist.duckdb"
    results_path: "./test_results.duckdb"
    
protocols:
  binkp:
    enabled: true
    port: 24554
    timeout: 10
    our_address: "2:5001/9999"
    
  ifcico:
    enabled: true
    port: 60179
    timeout: 10
    
  telnet:
    enabled: true
    port: 23
    timeout: 5
    
  ftp:
    enabled: false
    port: 21
    timeout: 10
    
  vmodem:
    enabled: false
    port: 3141
    timeout: 10
    
services:
  geolocation:
    provider: "ip-api"
    api_key: ""
    cache_ttl: 3600
    rate_limit: 150
    
  dns:
    workers: 5
    timeout: 5
    cache_ttl: 3600
    
cache:
  type: "badger"
  path: "/tmp/nodetest-cache"
  
logging:
  level: "debug"
  file: "./testdaemon.log"
  max_size: 10
  max_backups: 3
  max_age: 7

# CLI enabled for testing
cli:
  enabled: true
  host: "127.0.0.1"
  port: 2323
  max_clients: 5
  timeout: 300
  prompt: "> "
  welcome_message: |
    NodelistDB Test Daemon CLI v1.0.0
    Type 'help' for available commands.