# Test configuration for testdaemon with DuckDB
database:
  type: duckdb
  duckdb:
    nodes_path: ./nodelist.duckdb
    results_path: ./test_results.duckdb

daemon:
  test_interval: 1h
  workers: 5
  batch_size: 50

protocols:
  binkp:
    enabled: true
    port: 24554
    timeout: 10s
    our_address: "2:5001/5001"
    system_name: "NodelistDB Test Daemon"
    sysop: "Test Operator"
    location: "Test Location"

services:
  dns:
    workers: 10
    timeout: 5s
    cache_ttl: 24h
  geolocation:
    provider: ip-api
    api_key: ""
    cache_ttl: 168h
    rate_limit: 150

cache:
  enabled: true
  type: badger
  path: ./cache

logging:
  level: info
  file: ./testdaemon.log
  max_size: 100
  max_backups: 3
  max_age: 7

cli:
  enabled: true
  host: 127.0.0.1
  port: 2324