# NodelistDB Configuration Example
# =================================
# This configuration file shows all ACTUALLY IMPLEMENTED settings.
# 
# IMPORTANT: Most of this configuration is only used by the testdaemon.
# The parser and server applications currently only use the database section.

# ============================================================================
# DATABASE CONFIGURATION
# ============================================================================
# This section is used by ALL components (parser, server, testdaemon)

database:
  # Database type: "duckdb" or "clickhouse"
  type: duckdb
  
  # DuckDB Configuration
  # --------------------
  duckdb:
    # Main database path (used by parser and server)
    path: ./nodelist.duckdb
    
    # Separate databases for testdaemon (optional)
    # If not specified, testdaemon will use the main 'path' above
    nodes_path: ./nodelist.duckdb       # Read-only access to nodes
    results_path: ./test_results.duckdb # Test results storage
    
    # Performance settings
    memory_limit: 16GB
    threads: 8
    read_only: false  # Server will override this to true
    
    # Advanced tuning
    bulk_mode: false
    disable_wal: false
    checkpoint_threshold: 1GB
    wal_auto_checkpoint: 1000
    temp_directory: /tmp
  
  # ClickHouse Configuration (alternative to DuckDB)
  # ------------------------------------------------
  # Uncomment to use ClickHouse instead
  # clickhouse:
  #   host: localhost
  #   port: 9000
  #   database: nodelistdb
  #   username: default
  #   password: ""
  #   use_ssl: false
  #   
  #   # Connection pool
  #   max_open_conns: 10
  #   max_idle_conns: 5
  #   dial_timeout: 30s
  #   read_timeout: 5m
  #   write_timeout: 1m
  #   compression: lz4
  #   
  #   # Batch processing (for testdaemon)
  #   batch_size: 1000
  #   flush_interval: 30s

# ============================================================================
# TESTDAEMON-ONLY CONFIGURATION
# ============================================================================
# The following sections are ONLY used by the testdaemon application.
# Parser and server do NOT use these settings.

# Testing Daemon Configuration
# ----------------------------
daemon:
  # Test cycle settings
  test_interval: 1h  # Test cycle interval (1 hour)
  workers: 10
  batch_size: 100
  
  # Note: run_once, dry_run, and cli_only are set via command line flags

# Protocol Testing Configuration
# -------------------------------
protocols:
  binkp:
    enabled: true
    port: 24554
    timeout: 10s
    our_address: "2:5001/5001"  # Your FidoNet address
    system_name: "NodelistDB Test Daemon"  # SYS field
    sysop: "Test Operator"  # ZYZ field
    location: "Test Location"  # LOC field
  
  ifcico:
    enabled: true
    port: 60179
    timeout: 10s
    our_address: "2:5001/5001"
    system_name: "NodelistDB Test Daemon"  # System name in EMSI
    sysop: "Test Operator"  # Sysop name in EMSI
    location: "Test Location"  # Location in EMSI
  
  telnet:
    enabled: false
    port: 23
    timeout: 5s
  
  ftp:
    enabled: false
    port: 21
    timeout: 10s
  
  vmodem:
    enabled: false
    port: 3141
    timeout: 10s

# External Services Configuration
# --------------------------------
services:
  geolocation:
    provider: ip-api  # Options: ip-api, ipinfo, ipgeolocation
    api_key: ""       # Required for ipgeolocation, optional for ipinfo
    cache_ttl: 168h  # 7 days (7 * 24 hours)
    rate_limit: 150    # per minute (for external API calls)
  
  # DNS Resolution
  dns:
    workers: 20
    timeout: 5s
    cache_ttl: 24h  # 24 hours

# Cache Configuration
# -------------------
cache:
  enabled: true
  type: badger  # Options: badger, bolt
  path: /var/cache/nodetest

# Logging Configuration
# ---------------------
# Note: Only used by testdaemon. Parser and server use console output.
logging:
  level: info  # Options: debug, info, warn, error
  file: /var/log/nodetest-daemon.log
  max_size: 100     # MB
  max_backups: 7    # Number of old files to keep
  max_age: 30       # Days to retain old logs

# CLI Interface Configuration
# ---------------------------
# Telnet CLI for daemon control
cli:
  enabled: true
  host: 127.0.0.1
  port: 2323
  max_clients: 5
  timeout: 5m  # 5 minutes
  prompt: "> "
  welcome_message: |
    NodelistDB Test Daemon CLI v1.0.0
    Type 'help' for available commands.

# ============================================================================
# COMMAND-LINE FLAGS REFERENCE
# ============================================================================
#
# Parser flags (these override or supplement config):
#   -config config.yaml     # Path to this configuration file
#   -path /path/to/files    # Path to nodelist files (required)
#   -db /path/to/db         # Override database path
#   -batch 1000            # Batch size for inserts
#   -workers 4             # Number of concurrent workers
#   -recursive             # Scan directories recursively
#   -verbose              # Verbose output
#   -concurrent           # Enable concurrent processing
#   -create-fts           # Create Full-Text Search indexes
#   -rebuild-fts          # Only rebuild FTS indexes
#
# Server flags (these override or supplement config):
#   -config config.yaml     # Path to this configuration file
#   -host localhost        # HTTP server host
#   -port 8080            # HTTP server port
#   -db /path/to/db       # Override database path
#   -debug-sql            # Enable SQL query debugging
#
# Testdaemon flags:
#   -config config.yaml     # Path to this configuration file
#   -run-once             # Run one test cycle and exit
#   -dry-run              # Test without storing results
#   -cli-only             # Only run CLI interface, no automatic testing
