# NodelistDB Configuration
# This is the main configuration file for NodelistDB

database:
  type: duckdb  # Options: duckdb or clickhouse
  
  # DuckDB Configuration
  duckdb:
    path: /home/dp/nodelists/nodelistdb.duckdb
    memory_limit: 16GB
    threads: 8
    read_only: false
    
    # Performance settings for bulk loading
    bulk_mode: false           # Enable bulk loading optimizations
    disable_wal: false         # Disable Write-Ahead Logging
    checkpoint_threshold: 1GB  # Memory threshold before checkpoint
    wal_auto_checkpoint: 1000  # Pages before auto checkpoint (0 = disabled)
    temp_directory: /tmp       # Temporary files directory
  
  # ClickHouse Configuration (alternative to DuckDB)
  # Uncomment and configure if using ClickHouse
  # clickhouse:
  #   host: localhost
  #   port: 9000
  #   database: nodelistdb
  #   username: default
  #   password: ""
  #   use_ssl: false
  #   
  #   # Connection settings
  #   max_open_conns: 10
  #   max_idle_conns: 5
  #   dial_timeout: 30s
  #   read_timeout: 5m
  #   write_timeout: 1m
  #   compression: lz4  # Options: none, zstd, lz4, gzip