# NodelistDB Configuration - ClickHouse
# This configuration uses ClickHouse as the database backend

database:
  type: clickhouse  # Using ClickHouse instead of DuckDB
  
  # ClickHouse Configuration
  clickhouse:
    host: localhost
    port: 9000
    database: nodelistdb
    username: default
    password: ""
    use_ssl: false
    
    # Connection settings
    max_open_conns: 10
    max_idle_conns: 5
    dial_timeout: 30s
    read_timeout: 5m
    write_timeout: 1m
    compression: lz4  # Options: none, zstd, lz4, gzip

# Test Daemon Configuration
daemon:
  test_interval: 72h
  stale_test_threshold: 72h
  failed_retry_interval: 24h
  workers: 10
  batch_size: 100

# Protocol Testing Configuration
protocols:
  binkp:
    enabled: false
    port: 24554
    timeout: 10s
    our_address: "2:5001/5001"
  
  ifcico:
    enabled: true
    port: 60179
    timeout: 30s
    our_address: "2:5001/5001"
    system_name: "NodelistDB Test Daemon"
    sysop: "Test Operator"
    location: "Test Location"
  
  telnet:
    enabled: false
    port: 23
    timeout: 5s
  
  ftp:
    enabled: false
    port: 21
    timeout: 10s

# CLI Server Configuration
cli:
  enabled: true
  host: "127.0.0.1"
  port: 2323
  max_clients: 5
  timeout: 300s
  prompt: "> "
  welcome_message: |
    NodelistDB Test Daemon CLI
    Type 'help' for available commands.